### ISSUE TITLE
実行コマンド時 npm run build でエラーになった

### ISSUE THREAD

**Issue by iwkt** [iwkt/react-tailwindcss#1]
Tailwindの公式ドキュメントとYouTubeをみながらすすめました。
公式ドキュメントにもでもYouTubeでも
`npm install -D tailwindcss postcss autoprefixer`
となっています。
それで、YouTubeで進めていったところ、package.json にビルドコマンドの作成で
```
"scripts": {
    "build": "postcss styles.css -o dist.css"
  },
```
として
`npm run build`
を実行したところエラーが出てしまいました。
結局postcssをuninstall して postcss-cli を install。

`npm run build`でビルドできる様になりました。

そこで、仮説をたてました。
npm run buildなどコマンド入力で実行するときにはpostcss ではなく postss-cli が必要。gulpなどでwatchするならばpostcssでよい。

こんな考えで良いのでしょうか？

**Comment by reachscript-jak** [comment]
@iwkt 
今回のような内容のトラブル時ですが、

- 参考にしたYouTubeのリンク
- 出たエラーの内容

があると原因解決がスムーズかと思いますのでよろしくお願いします！🙏

また、質問の趣旨とはずれますが今後ReactでTailwindを使用していくならReact × Tailwind の環境構築も練習していただくと良いかと思います！（講義課題の意図はこちらでした）

別途自分でReact以外で使っていくことを考えての場合はもちろん大丈夫です🙆‍♂️

**Comment by iwkt** [comment]
たしかにその通りです。失礼いたしました。
エラーは postcss: command not found　です。

youtubeは以下リンクになります。
https://www.youtube.com/watch?v=mzRxqknA9Jg&t=0s
の13:30~14:00付近でエラーとなりました。

一通り、TailwindCSSの概要がつかめました。
今後TailwindCSS x Next.jsで環境構築を行なっていこうと考えております。

ありがとうございます。

**Comment by reachscript-jak** [comment]
「なるほど、動画のほうでもエラーになっているがその原因は？」ということですね！

> npm run buildなどコマンド入力で実行するときにはpostcss ではなく postss-cli が必要。gulpなどでwatchするならばpostcssでよい。

この感覚でほぼ問題ないですね！
コマンドとしてpostcssを実行するのか、内部的にpostcssを使用するのかの違いです👌

**Comment by iwkt** [comment]
その後、React x tailwindcss の環境を構築しました。そうすると npm run start 後はsaveしたタイミングでcssが更新されるようになりました。ありがとうございました。
