### ISSUE TITLE
npx tailwindcss init -p の -p ってなんだ

### ISSUE THREAD

**Issue by iwkt** [iwkt/react-tailwindcss#2]
初歩的な質問で恐縮です。
TailwindCSS.configやPostCSS.config を作成するときに
`npx tailwindcss init -p`と公式ドキュメントにあります。
この -p とは--save-prod　の短縮であっていますでしょうか。--save-prod　ですと-Pと大文字の様な気がします。

**Comment by reachscript-jak** [comment]
@iwkt 
こちらはtailwindcss init コマンドで用意されているオプションですね！
公式サイトにもさらって書いてありました！
![image](https://user-images.githubusercontent.com/44320334/175848671-a6814731-35cd-47c3-a5d5-5ee7141e5d26.png)
https://tailwindcss.jp/docs/installation

**Comment by iwkt** [comment]
ありがとうございます。
なるほど、このように　tailewindcssごとのようにオプションを付けることができるのですね。初めて知りました。
基本公式をよく見ると言うことですね。
