### ISSUE TITLE
VSCodeのワークスペースに機能拡張を含むコードの書き方

### ISSUE THREAD

**Issue by iwkt** [iwkt/react-tailwindcss#3]
以前 eslint を含んだ環境構築の時のようにgitに.vscodeを含めたいと考えました。
そこで、settings.jsonに Tailwind CSS IntelliSense　や　PostCSS Language　の記述をしようとしました。
しかし、どの様に書けば良いのかさっぱりわかりません。eslitのときはググるとその様な記事があったのでコピペしました。
今回はeslintにくらべると記事がなく途方に暮れています。

このようにワークスペースに機能拡張を共有するための記述は今後も頻繁にあるのではないかと思っています。
公式を見ても見当たらないときはどうすれば良いのか・・・orz

お願いします。

**Comment by reachscript-jak** [comment]
@iwkt 
ESLintの時にやったのは、「VSCodeの保存時にESLintを実行するようにする」という設定であり
「ESLintの拡張機能をインストールする」というものではありません。

今回やりたいことは恐らく「Tailwind CSS IntelliSense等をインストールしたい」だと思うのでその場合は「拡張機能をチームで共有する」というまた別の設定を行うことになります！
参考：https://qiita.com/otsuky/items/f46f5ee9eb11b3a9a4ba

**Comment by iwkt** [comment]
ありがとうございます。参考になりました。
